.TH I3LOCK-FANCY-C 1 2017-06-26

.SH NAME
.B i3lock-fancy-c
- Bash script around i3lock for fancy effect

.SH DESCRIPTION

Takes a screenshot of the desktop, blurs the background and adds a lock icon and
text. This blurred image is then given to \fBi3lock\fR as the lockscreen
background.

.SH SYNOPSIS

.B i3lock-fancy-c [options]

.SH OPTIONS

.TP
\fB-h, --help\fP
Display a help screen and exit.

.TP
\fB-g, --greyscale\fP
Set background to greyscale instead of color.

.TP
\fB-p, --pixelate\fP
Pixelate the background instead of blur, runs faster.

.TP
\fB-f <fontname>, --font <fontname>\fP
Set a custom font.

.SH SEE ALSO
\fBi3lock\fR(1)

.SH AUTHORS

JSP24
